# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XXKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XXKit

    pod 'Masonry'
    pod 'YYKit'
    pod 'MBProgressHUD'
    pod 'FMDB'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'TZImagePickerController'


  target 'XXKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XXKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
